config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user do
    resources :tweet
  end

  get '/search', to: 'user#search'
  patch '/search', to: 'user#follow'
  root 'user#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  # A follower is a user that follows another user.
  has_many :follower_followships,
           class_name: 'Followship',
           foreign_key: 'follower_id',
           dependent: :destroy

  # To see the users that the user follows, we reference them through the join
  # table.
  has_many :followees, through: :follower_followships

  has_many :followee_followships,
           class_name: 'Followship',
           foreign_key: 'followee_id',
           dependent: :destroy

  has_many :followers, through: :followee_followships



  #Field validations
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :username, length: { maximum: 16 }, presence: true, uniqueness: true
  validates_format_of :username, with: /\A(?=.*[a-z])[a-z\d]+\Z/i
  require 'uri'
  validates :email, presence: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: 'must be a valid email address' },
                    uniqueness: { case_sensitive: false }


  
  def follow(user)
    followees << user
  end

  def unfollow(followed_user)
    followees.delete followed_user
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        set_user_profile(current_user)
    end

    def new
    end

    def show
        @user = User.find_by(id: params[:id])
        set_user_profile(@user)
    end

    def search
        @user = User.new
    end

    def follow
        @user = User.find_by(username: params[:username])
        current_user.follow(@user)
    end

    def set_user_profile(user)
        @tweets = user.tweets
        @followers = user.followers
        @followees = user.followees
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:email,:password,:password_confirmation,:username, :name)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:email,:password,:password_confirmation, :name, :description, :current_password)
    end
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
  #   super
  #end
  
  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_followees.html.erb
<% user.followees.each do |followee| %>
<div class="row">
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title"><%= followee.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted">@<%= followee.username %></h6>
        </div>
    </div>
</div>
<% end %>

app/views/user/_followers.html.erb
<% user.followers.each do |follower| %>
    <div class="row">
        
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title"><%= link_to follower.name, user_path(follower) %></h5>
                <h6 class="card-subtitle mb-2 text-muted">@<%= follower.username %></h6>
            </div>
        </div>
    </div>
<% end %>

app/views/user/_profile.html.erb
<h2>List of tweets</h2>
<h3>Followers: </h3>

<h3>Following: </h3>

app/views/user/_search.html.erb
<%= form_with(url: search_path, method: "patch", class:"form-inline") do |f| %>
  <%= f.text_field :username, class:'form-control mr-sm-2' %>
  <%= f.submit "Follow", class: 'btn btn-outline-success my-2 my-sm-0' %>
<% end %>

app/views/user/_tweets.html.erb
<% tweets.each do |tweet| %>
    <div class="row">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title"><%= user.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted">@<%= user.username %></h6>
                <p class="card-text"><%= tweet.content %></p>
                <p class="card-text"><%= tweet.created_at %></p>
            </div>
        </div>
    </div>
<% end %>

app/views/user/index.html.erb
<div class="container">
        <div class="col">
            <%= link_to 'Tweet', new_user_tweet_path(current_user), class: "btn btn-primary" %>
        </div>
    <div class="row">
        
        <div class="col">
            <h2>tweets</h2>
            <%= render partial: "tweets" , locals: {user: current_user, tweets: @tweets } %>
        </div>
        
        <div class="col">
            
            <h2>Followers</h2>
            <%= render partial: "followers" , locals: {user: current_user } %>
        </div>
        <div class="col">
            
            <h2>Following</h2>
            <%= render partial: "followees" , locals: {user: current_user } %>
        </div>
    </div>
</div>

app/views/user/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            tweets:
            <%= render partial: "tweets", locals: {user: @user, tweets: @tweets } %>
        </div>
        <div class="col">
            
            followers:
            <%= render partial: "followers", locals: {user: @user } %>
        </div>
        <div class="col">
            
            following:
            <%= render partial: "followees", locals: {user: @user } %>
        </div>
    </div>
</div>